version: 2

conda:
  environment: docs/environment.yml

build:
   image: latest

submodules:
  include:
    - ext_libs/pybind11
    - ext_libs/vowpal_wabbit
    - ext_libs/vowpal_wabbit/ext_libs/armadillo-code
    - ext_libs/vowpal_wabbit/ext_libs/ensmallen
  recursive: false

python:
   version: "3.8"
   install:
   - method: pip
     path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
