version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

submodules:
  include:
    - ext_libs/pybind11
    - ext_libs/vowpal_wabbit
  recursive: false

conda:
  environment: environment.yml

python:
   install:
   - method: pip
     path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
