name: readthedocs
channels:
  - conda-forge
  - defaults
dependencies:
  - boost
  - eigen
  - flatbuffers
  - fmt
  - python=3.8
  - rapidjson
  - spdlog
  - zlib
  - pip:
    - furo
    - nbsphinx
    - pandas

