name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install gfortran on Linux
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install gfortran

    - name: Install gfortran on Windows
      if: ${{ matrix.platform == 'windows-latest' }}
      run: |
        choco install mingw --force
        echo "CMAKE_MAKE_PROGRAM=C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/make.exe" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "CMAKE_C_COMPILER=C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/gcc.exe" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "CMAKE_CXX_COMPILER=C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/g++.exe" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "CMAKE_Fortran_COMPILER=C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/gfortran.exe" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Install gfortran on MacOS
      if: ${{ matrix.platform == 'macos-latest' }}
      run: |
        brew install gcc
        echo "CMAKE_MAKE_PROGRAM=make" >> $GITHUB_ENV
        echo "CMAKE_C_COMPILER=/usr/local/bin/gcc-11" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER=/usr/local/bin/g++-11" >> $GITHUB_ENV
        echo "CMAKE_Fortran_COMPILER=/usr/local/bin/gfortran" >> $GITHUB_ENV
  

    - name: Set VCPKG_DEFAULT_TRIPLET on Windows
      if: ${{ matrix.platform == 'windows-latest' }}
      run: |
        "SKBUILD_CONFIGURE_OPTIONS=-DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded" >> $env:GITHUB_ENV

    - name: Install pkg-config on MacOS
      if: ${{ matrix.platform == 'macos-latest' }}
      run: brew install pkg-config

    - name: Build and install
      run: pip install --verbose .
      env:
        CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/ext_libs/vcpkg/scripts/buildsystems/vcpkg.cmake
        VCPKG_FORCE_DOWNLOADED_BINARIES: true
        MACOSX_DEPLOYMENT_TARGET: "10.13"

    - name: Install dev dependencies
      run: pip install -r requirements-dev.txt

    - name: Test
      run: pytest

    - name: Typecheck
      run: mypy