name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Checkout specific submodules
      run: |
        cd ext_libs/vowpal_wabbit
        git submodule update --init ext_libs/armadillo-code
        git submodule update --init ext_libs/ensmallen

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set VCPKG_DEFAULT_TRIPLET on Windows
      if: ${{ matrix.platform == 'windows-latest' }}
      run: |
        "SKBUILD_CONFIGURE_OPTIONS=-DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded" >> $env:GITHUB_ENV

    - name: Install pkg-config on MacOS
      if: ${{ matrix.platform == 'macos-latest' }}
      run: brew install pkg-config

    - name: Build and install
      run: pip install --verbose .
      env:
        CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/ext_libs/vcpkg/scripts/buildsystems/vcpkg.cmake
        VCPKG_FORCE_DOWNLOADED_BINARIES: true
        MACOSX_DEPLOYMENT_TARGET: "10.13"

    - name: Install dev dependencies
      run: pip install -r requirements-dev.txt

    - name: Test
      run: pytest

    - name: Typecheck
      run: mypy
